### PR TITLE
v1.5.x (rebased PR 134)

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
This is a flattened / rebased version of PR #134.

### CODE REVIEW

**Comment by dirkcuys** [comment]
@dmitrizagidulin - when I check out this branch and do:
```
rm -r node_modules
npm ci
npm start
npm start android
```
Everthing gets to the point where the app opens on the emulator, but I get the following error:

>[Fri Jun 10 2022 09:45:18.978]  ERROR    TypeError: The first parameter (url) must be a string.
>[Fri Jun 10 2022 09:45:18.978]  ERROR    Invariant Violation: "main" has not been registered. This can happen if:
> Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by dirkcuys** [comment]
It seems like [these two lines](https://github.com/digitalcredentials/learner-credential-wallet/pull/174/commits/7c2ebf4156a034ef8924d7c01d254aa81c02d498#diff-52d032eee0ed27ab68547594a9d1759903121d8e5177db68ae3556aa614dc620R63-R64):

```typescript
loader.addStatic(obCtx.CONTEXT_URL_V3_JFF_V1, obCtx.CONTEXT_V3);
loader.addStatic(obCtx.CONTEXT_URL_V3_IMS, obCtx.CONTEXT_V3); 
```
are using a variable that doesn't exists in [open-badges-context](https://github.com/digitalcredentials/open-badges-context/blob/main/js/index.js). It also isn't in the code installed through npm ci.

**Comment by dmitrizagidulin** [comment]
@dirkcuys - ahhh ok, when I added the `open-badges-context` module to package.json, it didn't make it to the package lock.
Thanks

**Comment by dmitrizagidulin** [comment]
Closing - not needed (Dirk's original PR already resolved conflicts).

**Pull request closed without merging**
