### PR TITLE
Update add credential screen

### PR DESCRIPTION
**Pull request by sethduffin**
Issues: 
* #250 
* #249

PT Stories:
* https://www.pivotaltracker.com/story/show/183158668
* https://www.pivotaltracker.com/story/show/183158675
* https://www.pivotaltracker.com/story/show/183701290

## Changes
A credential can now be added through a **supported format** containing the any of the specified **content types**.

**Supported Formats**:
 - QR Code
 - URL QR Code
 - URL
 - File
 - Raw Text

**Content Types**:
 - JSON
 - VPQR

## Preview
| Add Screen | Active |
| --- | --- |
| Simulator Screen Shot - iPhone 13 - 2022-11-04 at 16 14 45 | Simulator Screen Shot - iPhone 13 - 2022-11-04 at 16 15 21 |

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Comment by sethduffin** [comment]
@dmitrizagidulin I've updated this PR with the new add credential logic, but am waiting on Brandon F for the UI changes.

**Comment by sethduffin** [comment]
@dmitrizagidulin Ok, this PR is ready to merge!

**Comment by sethduffin** [comment]
Actually hold off for a sec, it looks like the Android build check is failing. I'll need to investigate. (sorry for the premature notification)

**Pull request merged**
