### PR TITLE
Updated app display name

### PR DESCRIPTION
**Pull request by sethduffin**
The app display name was previously `edu-wallet` but this PR updates it to `EDU Wallet`

### CODE REVIEW

**Comment by bmuramatsu** [comment]
@sethduffin @dmitrizagidulin actually we decided on eduWallet, all one word. Thanks for being proactive here, but we'll need to adjust.

**Comment by sethduffin** [comment]
> @sethduffin @dmitrizagidulin actually we decided on eduWallet, all one word. Thanks for being proactive here, but we'll need to adjust again and throughout the app.
> 
> 
> 
> Also how is the text on the login screen generated? EDU Wallet -> eduWallet is that text in a file somewhere or is it a graphic.

Not a problem, I'll update the app name and start screen text to `eduWallet`.

**Comment by bmuramatsu** [comment]
Also on the About Screen. I don't think there are any other visible uses of
the name.

Thanks!

**Comment by sethduffin** [comment]
Sounds good. I've added `displayName` to the app config and updated those elements to reference that key. This will ensure consistency and make potential renames easier.

**Review by dmitrizagidulin — APPROVED** [review]
👍

**Pull request merged**
