### PR TITLE
Add screenshots to README

### PR DESCRIPTION
**Pull request by fields37**
Added 4 screenshots showing the app in action to the README file, arranged in a line above the "GOALS" section as per https://github.com/digitalcredentials/learner-credential-wallet/issues/267

### CODE REVIEW

**Comment by sembrat** [comment]
Happy to make the adjustment to the branch to add in some more descriptive alt-text. I don't believe I have write-access to this repo or org right meow.

**Comment by fields37** [comment]
Hi @sembrat, I just added in more descriptive alt-text for the images. If you have any additional suggested changes to the descriptions definitely let me know.

**Review by bmuramatsu — APPROVED** [review]
Works for me.

**Comment by bmuramatsu** [comment]
@dmitrizagidulin I'm not sure if the Lint errors are meaningful, can you please review. We're trying to add screenshots with alt text to the project description (readme) page.

**Comment by sembrat** [comment]
Alt text looks good - thanks!

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Pull request merged**
