### PR TITLE
[Old] Upgraded React Native to 0.64.1

### LINKED ISSUE #72: Upgrade react-native to >= 0.64.1
Upgrade react-native to version 0.64.1 or later (to get rid of Dependabot alert https://github.com/advisories/GHSA-7f53-fmmv-mfjv )

### PR DESCRIPTION
**Pull request by sethduffin**
Closes #72

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Comment by dmitrizagidulin** [comment]
@sethduffin - amazing work here. Do you mind re-generating the package-lock.json to get rid of the merge conflicts?

**Comment by sethduffin** [comment]
I've updated the package-lock.json and refactored one of our components to fix the typescript lint error (some types were updated in the new RN version).

**Comment by sethduffin** [comment]
This MR has been replaced and split into two new MRs:
* #132
* #133

Closing this MR.

**Pull request closed without merging**
