### PR TITLE
Extract issuer registry into separate module

### PR DESCRIPTION
**Pull request by sethduffin**
The code has been migrated to https://github.com/digitalcredentials/issuer-registry-client

This PR should remain a draft until https://github.com/digitalcredentials/issuer-registry-client/pull/1 has been merged into main and the repo is added as a dependency.

### CODE REVIEW

**Comment by sethduffin** [comment]
@dmitrizagidulin I'll update this PR (fix lint & mark as ready) once this PR makes it in: https://github.com/digitalcredentials/issuer-registry-client/pull/1

**Comment by dmitrizagidulin** [comment]
@sethduffin thanks. issuer-registry-client is now published on npm, so go ahead.

**Comment by sethduffin** [comment]
@dmitrizagidulin Ok, this should b ready to go!

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Pull request merged**
