### PR TITLE
Conversions between markdown and html complete

### PR DESCRIPTION
**Pull request by jmcioffi4**
Issue/Project Board Link: https://github.com/digitalcredentials/learner-credential-wallet/issues/456

Waiting on: Allowed Tags list (for now is set to all)

Reviewer(s): Please pull code and test, use `app/lib/credentialDisplay/openBadgeCredential.tsx:46` as your example using both HTML and Markdown.

Reasoning: We couldn't find a library to sanitize the markdown, so we convert it to HTML, sanitize it, then render it.

### CODE REVIEW

**Comment by kayaelle** [comment]
@jmcioffi4 -  can you explain more about what you mean by "allowed tags"?

**Comment by dmitrizagidulin** [comment]
> @jmcioffi4 - can you explain more about what you mean by "allowed tags"?

So, the process of "sanitizing" HTML or Markdown basically looks like - you pass the library a list of allowed HTML elements or Markup tags. Things like - allow headers, bold, italic, etc.  
So there's many libraries that let you to specify the allow list, like https://help.hcltechsw.com/connections/v65/admin/secure/sec_acf_whitelist_element.html

However, it turns out that the library we're using https://github.com/remarkjs/react-markdown#security (or its hook-based equivalent, https://github.com/remarkjs/react-remark all pre-sanitize the Markdown, so we don't need to take additional steps (don't need an explicit allow list yet).

**Comment by dmitrizagidulin** [comment]
> Reasoning: We couldn't find a library to sanitize the markdown, so we convert it to HTML, sanitize it, then render it.

@jmcioffi4 As mentioned in other issues, the various Markdown-to-React Component libraries (even though they don't expose sanitization functionality explicitly) are sufficiently secure for us to use here.
So, my advice is - don't use the HTML sanitize route, try directly Markdown to Component. (We'll need to support more tags than just `a` links, etc).

**Comment by dmitrizagidulin** [comment]
Ah, yeah, in fact, it looks like PR #465 does exactly that. So this draft PR can be closed.

**Pull request closed without merging**
