### PR TITLE
Rename ios bundle

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
This PR contains a number of edits (mostly having to do with renaming the app bundle) required to get the app into the iOS store.

### CODE REVIEW

**Comment by sethduffin** [comment]
I believe there's one more case change `eduwallet.xcworkspace` → `eduWallet.xcworkspace` (may just be a case-insensitive problem on my os), but after updating that, I was able to build the app.

**Review by sethduffin — CHANGES_REQUESTED** [review]
I believe there's one more case change `eduwallet.xcworkspace` → `eduWallet.xcworkspace` (may just be a case-insensitive problem on my os), but after updating that I was able to build the app.

**Review by sethduffin — APPROVED** [review]
This branch works great on my side now. Thanks!

**Comment by dmitrizagidulin** [comment]
@sethduffin - thanks! Merging.

**Pull request merged**
